export const GET_WAIT_TIMES = 'GET_WAIT_TIMES';
export const UPDATE_PARKS = 'UPDATE_PARKS';
export const UPDATE_BEST_PARK = 'UPDATE_BEST_PARK';
export const UPDATE_MAGIC_KINGDOM = 'UPDATE_MAGIC_KINGDOM';
export const UPDATE_EPCOT = 'UPDATE_EPCOT';
export const UPDATE_HOLLYWOOD_STUDIOS = 'UPDATE_HOLLYWOOD_STUDIOS';
export const UPDATE_ANIMAL_KINGDOM = 'UPDATE_ANIMAL_KINGDOM';